#!/usr/bin/env python

"""Simulated run of profiling-counters based searcher (does not need KTT)

Usage:
  simulated-profiling-searcher.py -o <KTT_output> --oc <output_compute> --mp <multiprocessors> --co <cuda_cores> (-s <statistics> | --cm <completemappning> | --dt <decision-tree-modelFiles> | --ls <least-squares-modelFiles>) --ic <input_compute> -p <time_index> -t <tuningpar_interval> -c <counters_interval> (-i iteration) (-e expriment) [--compute_bound | --memory_bound]


Options:
  -h Show this screen.
  -o Raw tuning data in CSV file, output from KTT (must include profiling counters).
  --oc Compute capability of device where output CSV has been produced
  --mp Number of multiprocessors on GPU where output CSV has been produced
  --co Number of CUDA cores on GPU where output CSV has been produced
  --cm Complete mapping of tuning parameters to profile counters (mutually exclusive with statistics).
  --dt Decision tree generated by mlKTTPredictor.py (*.sav)
  --ls Least squares nonlinear models generated by create_least_squares_models.R.
  --ic Compute capability of device from which statistics/complete mapping/knowledge base were computed.
  -p Index of time information.
  -t Interval <i:j,[k,l,m]>  or i:j of tuning parameters indices (for example- 1:5,[7,9]  means cols 1 to 4 and 7 and 9).
  -c Interval <i:j,[k,l,m]>  or i:j of profiler counter indices (for example- 1:5,[7,9]  means cols 1 to 4 and 7 and 9).
  -e Number of experiments
  -i Number of iterations
  --compute-bound Indicates the problem is compute-bound
  --memory-bound Indicates the problem is memory-bound
"""

from docopt import docopt
import random
import math
from operator import add
from base import *
import glob
from mlKTTPredictor import *
import numpy  as np

# configuration of emulated searching: number of experiments (used for better
# statistical power and number of iterations made by profile-based and random
# searcher)
EXPERIMENTS = 1
ITERS = 1

DEBUG = 0
VERBOSE = 0

# determines how many time the profiling is spanned
# 1 = profile all the time (lowest iters), 5 = profile 20 % runs, seems to
# be close to the lowest iters with much better runtime
NONPROFILE_BATCH = 5

############## main function emulating KTT tuning and search  ##################
if __name__ == '__main__':

    # parse command line
    arguments = docopt(__doc__)
    tuningOutput = open(arguments['-o'])
    ccCounters = float(arguments['--oc'])
    multiprocessors = int(arguments['--mp'])
    cudaCores = int(arguments['--co'])
    EXPERIMENTS = int(arguments['-e'])
    ITERS = int(arguments['-i'])

    if arguments['--dt']:
        trainedKnowledgeBase = str(arguments['--dt'])
    elif arguments['--ls'] :
        modelFiles = glob.glob(arguments['--ls']+"-model_*.csv")
    elif arguments['--cm'] :
        completeMapping = open(arguments['--cm'])
    ccInput = float(arguments['--ic'])
    timeIdx = int(arguments['-p'])
    tuningRange = arguments['-t']
    countersRange = arguments['-c']

    try:
        rangeT = eval("np.r_[" + tuningRange + "]")
        rangeC = eval("np.r_[" + countersRange + "]")
    except:
        print("Intervals must be in format <i:j,[k,l,m]> or i:j (for example- 1:5,[7,9]  means cols 1 to 4 and 7 and 9).")
        exit()

    if arguments.get('--compute_bound') :
        setComputeBound()
    if arguments.get('--memory_bound') :
        setMemoryBound()

    # read offline tuning data
    words = tuningOutput.readline().split(',')
    profilingCountersTuning = []

    for i in rangeC:
        profilingCountersTuning.append(words[i].rstrip())
    #print("profilingCountersTuning: ", profilingCountersTuning)
    tuningParams = []
    for i in rangeT:
        tuningParams.append(words[i])
    #print("tuningParams: ", tuningParams)
    time = []
    configurationsData = []
    countersData = []
    for line in tuningOutput.readlines():
        words = line.split(',')
        if len(words) <= 1: break

        time.append(float(words[timeIdx]))
        tunRow = []
        for i in rangeT:
            tunRow.append(float(words[i]))
        configurationsData.append(list(tunRow))
        profRow = []
        for i in rangeC:
            profRow.append(float(words[i]))
        countersData.append(list(profRow))

    # load statistics
    if arguments['--ls'] :
        [tuningParams, tuningparamsAssignments, conditionsAllModels, profilingCountersAssignments, profilingCountersStats] = loadModels(modelFiles)
        completeMappingCounters = makePredictions(configurationsData, tuningparamsAssignments, conditionsAllModels, profilingCountersAssignments)
    elif arguments['--cm'] :
        profilingCountersStats = loadCompleteMappingCounters(completeMapping, rangeC)
        completeMappingCounters = loadCompleteMapping(completeMapping, rangeT, rangeC)
    elif arguments['--dt']:
        profilingCountersStats = readPCList(trainedKnowledgeBase + ".pc")

    # force determinism (for easier debugging)
    random.seed(0)

    # perform the search
    timesAvgRnd = [0.0]*ITERS
    timesStdRnd = []
    timesAvgWeighted = [0.0]*ITERS
    timesStdWeighted = []
    for i in range(0, ITERS) :
        new = []
        timesStdRnd.append(new)
        new2 = []
        timesStdWeighted.append(new2)

    for e in range(0, EXPERIMENTS) :
        bestTime = 1000000000
        bestRndTime = bestTime
        lastBestTime = bestTime
        lastBestIdx = 0
        lastLastBestIdx = 1
        notImproved = 0
        scoreDistrib = [1.0]*len(configurationsData)
        for i in range(0, ITERS):
            # perform random search
            rndIdx = randomSearchStep(len(configurationsData))
            idx = weightedRandomSearchStep(scoreDistrib, len(configurationsData))

            # simulate KTT tuning
            myTime = time[idx]
            scoreDistrib[idx] = 0.0
            if myTime < bestTime:
                bestTime = myTime
                lastBestIdx = idx
            if VERBOSE > 0 :
                print("Searching weighted ", i, idx, myTime, bestTime)
                print("Searching random ", i, rndIdx, time[rndIdx])

            #XXX here we can simulate profiling of only some runs
            if i % NONPROFILE_BATCH == 0 :
                if lastBestIdx != lastLastBestIdx :
                    idx = lastBestIdx
                    lastLastBestIdx = idx
            #if (myTime < lastBestTime) or (random.random() < 1) :#0.1):
            #if (myTime < lastBestTime) or (notImproved >= 4) :
                bottlenecks = analyzeBottlenecks(profilingCountersTuning, countersData[idx], ccCounters, multiprocessors, cudaCores);
                changes = computeChanges(bottlenecks, profilingCountersStats, ccInput)
                if arguments['--ls'] :
                    scoreDistrib = scoreTuningConfigurationsExact(changes, tuningParams, configurationsData[idx], configurationsData, completeMappingCounters, scoreDistrib)
                elif arguments['--cm'] :
                    scoreDistrib = scoreTuningConfigurationsExact(changes, tuningParams, configurationsData[idx], configurationsData, completeMappingCounters, scoreDistrib)
                elif arguments['--dt'] :
                    scoreDistrib = scoreTuningConfigurationsPredictor(changes, tuningParams, configurationsData[idx], configurationsData, scoreDistrib, trainedKnowledgeBase)
                lastBestTime = myTime
                notImproved = 0
            else :
                notImproved = notImproved + 1


            # compute statistics
            if VERBOSE > 0 :
                timesNW = 0.0
                timesW = 0.0
                nonzeros = 0
                for j in range(0, len(time)) :
                    if (scoreDistrib[j] != 0.0) :
                        timesNW = timesNW + time[j]
                        nonzeros = nonzeros + 1
                    timesW = timesW + time[j] * scoreDistrib[j]
                timesNW = timesNW / nonzeros
                timesW = timesW / sum(scoreDistrib)
                print("Times W/NW: " + str(timesW) + "/" + str(timesNW))
                print("To explore: " + str(nonzeros) + "/" + str(len(time)))

            timesAvgWeighted[i] = timesAvgWeighted[i] + bestTime
            timesStdWeighted[i].append(bestTime)
            rndTime = time[rndIdx]
            bestRndTime = min(bestRndTime,  rndTime)
            timesAvgRnd[i] = timesAvgRnd[i] + bestRndTime
            timesStdRnd[i].append(bestRndTime)

    print("#experiment, avg rnd time +- stdev, avg w time +- stdev")
    for i in range(0, ITERS) :
        stdW = 0.0
        stdRnd = 0.0
        for j in range(0, EXPERIMENTS) :
            stdW = stdW + (timesStdWeighted[i][j] - (timesAvgWeighted[i] / EXPERIMENTS))**2
            stdRnd = stdRnd + (timesStdRnd[i][j] - (timesAvgRnd[i] / EXPERIMENTS))**2
        stdW = math.sqrt(stdW / EXPERIMENTS)
        stdRnd = math.sqrt(stdRnd / EXPERIMENTS)
        print(str(i+1) + ", " + str(timesAvgRnd[i] / EXPERIMENTS) + "+-" + str(stdRnd) + ", " + str(timesAvgWeighted[i] / EXPERIMENTS) + "+-" + str(stdW))

    if DEBUG > 0:
        # drain some statistics for debugging...
        print("Computing statistics of biasing for each tuning conf., this may take some time...")
        timesWavg = 0.0
        timesNW = 0.0
        bestTime = min(time)
        perfHistVal = [0.0]*10
        perfHistNum = [0]*10
        for i in range(0, len(configurationsData)):
            bottlenecks = analyzeBottlenecks(profilingCountersTuning, countersData[i], ccCounters)
            changes = computeChanges(bottlenecks, profilingCountersStats, ccInput)
            scoreDistrib = [1.0]*len(configurationsData)
            if arguments['--cm'] :
                scoreDistrib = scoreTuningConfigurationsExact(changes, tuningParams, configurationsData[idx], configurationsData, completeMappingCounters, scoreDistrib)
            elif arguments['--dt'] :
                scoreDistrib = scoreTuningConfigurationsPredictor(changes, tuningParams, configurationsData[idx], configurationsData, scoreDistrib, trainedKnowledgeBase)
            elif arguments['--ls'] :
                scoreDistrib = scoreTuningConfigurationsExact(changes, tuningParams, configurationsData[idx], configurationsData, completeMappingCounters, scoreDistrib)
            timesW = 0.0
            for j in range(0, len(time)) :
                timesNW = timesNW + time[j]
                timesW = timesW + time[j] * scoreDistrib[j]
            timesNW = timesNW / len(time)
            timesW = timesW / sum(scoreDistrib)
            print("Conf. " + str(i) + ": rel. perf " + str(bestTime/time[i]) + " times W/NW " + str(timesW/timesNW))
            timesWavg = timesWavg + timesW/timesNW
            histIdx = min(int(10*bestTime/time[i]), 9) # 1.0 into index 9
            perfHistVal[histIdx] = perfHistVal[histIdx] + timesW/timesNW
            perfHistNum[histIdx] = perfHistNum[histIdx] + 1
        print("Average times W/NW " + str(timesWavg / len(configurationsData)))
        for i in range(0, 10) :
            if perfHistNum[i] > 0 :
                print("Perf " + str(i/10.0) + "-" + str((i+1)/10.0) + ": " + str(perfHistVal[i] / perfHistNum[i]))


